// Euler problem #2
// Even Fibonacci numbers
// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.


var fiboSeq = [1,2];

var sumOfEvenFibo = 2;

for (i = 3; i < 4000000; i = fiboSeq[fiboSeq.length - 1] + fiboSeq[fiboSeq.length - 2]) {
	fiboSeq[fiboSeq.length] = i;

		if (i % 2 === 0) {
			sumOfEvenFibo += i;
		}
}

console.log("The sum of even-valued fibonacci numbers is " +sumOfEvenFibo);